#!/bin/bash
EXTDIR=ext/chasm
LOFILE=$EXTDIR/chasm.lo

#remove existing ext/chasm/chasm.lo target
sed -i 's/^\(ext\/chasm\/.*\|.*ext\/chasm\/chasm.lo\s*\)$//' Makefile

#add new target
echo "
chasm.lo: $EXTDIR/chasm.asm
	echo \"# Generated by libtool (not really)\" > $LOFILE
	echo \"pic_object='.libs/chasm.o'\" >> $LOFILE
	echo \"non_pic_object=none\" >> $LOFILE
	cd $EXTDIR && nasm -f elf64 -o .libs/chasm.o chasm.asm
" >> Makefile
